-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 09:43:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attachments` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `subtype` VARCHAR(45) NOT NULL,
  `size` INT(11) NOT NULL,
  `md5` VARCHAR(32) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `copyright` VARCHAR(255) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `embed` TEXT NULL DEFAULT NULL,
  `profile` VARCHAR(45) NOT NULL DEFAULT 'default',
  `width` INT(10) UNSIGNED NULL DEFAULT '0',
  `height` INT(10) UNSIGNED NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `meta` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `meta` VARCHAR(255) NULL,
  `header` TEXT NULL,
  `body` TEXT NULL,
  `publish_date` DATETIME NOT NULL,
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attachments_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attachments_posts` (
  `attachment_id` BIGINT(20) NOT NULL,
  `post_id` INT UNSIGNED NOT NULL,
  `order` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`attachment_id`, `post_id`),
  INDEX `fk_attachments_has_posts_posts2_idx` (`post_id` ASC),
  INDEX `fk_attachments_has_posts_attachments2_idx` (`attachment_id` ASC),
  CONSTRAINT `fk_attachments_has_posts_attachments2`
    FOREIGN KEY (`attachment_id`)
    REFERENCES `attachments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attachments_has_posts_posts2`
    FOREIGN KEY (`post_id`)
    REFERENCES `posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
